# Generated by Django 4.1.2 on 2023-03-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez', '0002_item_remove_profile_loction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ez.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(blank=True, to='ez.item'),
        ),
    ]
