# Generated by Django 4.1.2 on 2023-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez', '0003_alter_business_categories_alter_category_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='I.png', upload_to='profile_img'),
        ),
    ]
