# Generated by Django 4.1.7 on 2023-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_profile_isbuisness"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Buisness",
            new_name="Business",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="isBuisness",
            new_name="isBusiness",
        ),
    ]
