# Generated by Django 4.1.7 on 2023-03-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_business_businessnameslug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(null=True, to="backend.category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="items",
            field=models.ManyToManyField(null=True, to="backend.item"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="isBusiness",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.business",
            ),
        ),
    ]
