# Generated by Django 4.1.7 on 2023-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_alter_business_categories_alter_category_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(to="backend.category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="items",
            field=models.ManyToManyField(to="backend.item"),
        ),
    ]
