# Generated by Django 4.1.7 on 2023-03-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_business_categories_alter_category_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="items",
            field=models.ManyToManyField(blank=True, to="backend.item"),
        ),
    ]
