# Generated by Django 4.1.7 on 2023-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_alter_business_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(blank=True, to="backend.category"),
        ),
    ]
