# Generated by Django 4.1.7 on 2023-03-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_business_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="businessCategory",
            field=models.CharField(default="", max_length=25),
        ),
    ]
