# Generated by Django 4.1.7 on 2023-04-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_business_businesscategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="businessName",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="businessNameSlug",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
