# Generated by Django 4.1.7 on 2023-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_alter_business_businessname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, upload_to="item_image"),
        ),
    ]
