# Generated by Django 4.1.7 on 2023-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_alter_category_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="items",
            field=models.ManyToManyField(blank=True, to="backend.item"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default="blank-profile-picture.png", upload_to="item_image"
            ),
        ),
    ]
