# Generated by Django 4.1.7 on 2024-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_alter_category_items_alter_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="businessPhoto",
            field=models.FileField(default="", upload_to="photos"),
        ),
    ]
