# Generated by Django 4.1.7 on 2024-04-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_business_businessphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="businessPhoto",
            field=models.FileField(default="", upload_to="item_image"),
        ),
    ]
